# Generated by Django 5.1 on 2025-10-09 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('bodeguero', 'Bodeguero'), ('jefe_bodega', 'Jefe de Bodega'), ('auditor', 'Auditor'), ('administrador', 'Administrador'), ('supervisor', 'Supervisor')], help_text='Tipo de cargo que determina permisos automáticos', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bodega',
            field=models.ForeignKey(blank=True, help_text='Bodega asignada (requerida para bodegueros y jefes de bodega)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_inventario.bodega'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del usuario', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT del usuario (formato: 12345678-9)', max_length=20, null=True, unique=True),
        ),
    ]
