# Generated by Django 5.2.7 on 2025-10-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0002_cargo_tipo_customuser_bodega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='precio_compra',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT del usuario (formato: 12345678-9)', max_length=10, null=True, unique=True),
        ),
    ]
