# Generated by Django 5.2.7 on 2025-10-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0004_lote_precio_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariolote',
            name='cantidad_actual',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
