# Generated by Django 5.2.7 on 2025-10-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0005_alter_inventariolote_cantidad_actual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='cantidad_inicial',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='inventariolote',
            name='cantidad_actual',
        ),
    ]
