# Generated by Django 5.2.7 on 2025-10-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0006_rename_cantidad_inicial_lote_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesalida',
            name='producto',
        ),
    ]
