# Generated by Django 5.2.7 on 2025-10-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0007_remove_detallesalida_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromerma',
            name='observaciones_aprobacion',
        ),
        migrations.AlterField(
            model_name='registromerma',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
