# Generated by Django 5.2.7 on 2025-10-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0008_remove_registromerma_observaciones_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_persona_juridica',
            field=models.BooleanField(default=True, help_text='True para persona jurídica, False para persona natural'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='es_persona_juridica',
            field=models.BooleanField(default=True, help_text='True para persona jurídica, False para persona natural'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
