# Generated by Django 5.2.7 on 2025-10-23 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0009_cliente_es_persona_juridica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMinimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_minima', models.DecimalField(decimal_places=3, help_text='Cantidad mínima de stock requerida', max_digits=10)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_minimo', to='gestion_inventario.producto')),
            ],
            options={
                'verbose_name': 'Stock Mínimo',
                'verbose_name_plural': 'Stocks Mínimos',
            },
        ),
    ]
