# Generated by Django 5.2.7 on 2025-10-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0010_stockminimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallemerma',
            name='descripcion',
        ),
    ]
