# Generated by Django 5.2.7 on 2025-10-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0011_remove_detallemerma_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='activo',
            field=models.BooleanField(default=True, help_text='True si el lote está activo, False si está inactivo'),
        ),
        migrations.AddField(
            model_name='lote',
            name='fecha_inactivacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando el lote se volvió inactivo', null=True),
        ),
    ]
