# Generated by Django 5.2.7 on 2025-11-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0012_lote_activo_lote_fecha_inactivacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_por_lote',
            field=models.IntegerField(default=1),
        ),
    ]
