# Generated by Django 5.1 on 2025-11-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0013_alter_producto_cantidad_por_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='True si el producto está activo, False si está inactivo'),
        ),
    ]
