# Generated by Django 5.1 on 2025-11-20 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0014_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaproducto',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_inventario.conductor'),
        ),
    ]
