# Generated by Django 5.1 on 2025-11-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0015_salidaproducto_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del conductor', null=True),
        ),
    ]
