# Generated by Django 5.1 on 2025-11-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0016_conductor_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemerma',
            name='valor_merma',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor monetario de la merma calculado', max_digits=15),
        ),
        migrations.AddField(
            model_name='registromerma',
            name='valor_total_merma',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total monetario de la merma', max_digits=15),
        ),
    ]
