# Generated by Django 5.1 on 2025-11-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0017_detallemerma_valor_merma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, help_text='True si el cliente está activo, False si está inactivo'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='activo',
            field=models.BooleanField(default=True, help_text='True si el conductor está activo, False si está inactivo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True, help_text='True si el proveedor está activo, False si está inactivo'),
        ),
    ]
