# Generated by Django 5.1 on 2025-11-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0018_cliente_activo_conductor_activo_proveedor_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_expires',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiración del token', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token',
            field=models.CharField(blank=True, help_text='Token para recuperación de contraseña', max_length=100, null=True),
        ),
    ]
